### ISSUE TITLE
GlyphRun.bbox is all Infinity when there is a blank glyph

### ISSUE THREAD

**Issue by khaledhosny** [devongovett/fontkit#103]
When the glyph run has a blank glyph (e.g. space) `GlyphRun.bbox` will be:
```
BBox {
  minX: -Infinity,
  minY: -Infinity,
  maxX: Infinity,
  maxY: Infinity }
```

Which seems to be caused by the `bbox` of the blank glyph.

**Comment by AgainPsychoX** [comment]
Still an issue for normal glyphs

**Comment by AgainPsychoX** [comment]
For example, I use Lato (Regular), TTF files. Both LatoWeb and Lato _(idk the diff tbh)_ Regular set have `bbox` with `Infinity`ies instead 0 or something more natural...

```js
const fk = require('fontkit');
const f = fk.openSync('C:\\Windows\\Fonts\\LatoWeb-Regular.ttf'); // or "C:\\Users\\<username>\\AppData\\Local\\Microsoft\\Windows\\Fonts\\Lato-Regular.ttf"
const g = f.glyphForCodePoint(' '.codePointAt(0));
console.log(g.bbox);
/*
BBox {
  minX: Infinity,
  minY: Infinity,
  maxX: -Infinity,
  maxY: -Infinity
}
*/
```

Fonts attached: [LatoWeb-Regular.zip](https://github.com/foliojs/fontkit/files/6698775/LatoWeb-Regular.zip)
