### ISSUE TITLE
very large memory footprint?

### ISSUE THREAD

**Issue by Pomax** [devongovett/fontkit#11]
It would appear that fontkit, without loading in any fonts, takes up some 970MB of RAM, which is... pretty much impossibly large, since it leaves no RAM to actually run a program with on affordable VMs.

I simply used the following code:
```
var fontkit = require("fontkit");
var readline = require('readline');
var rl = readline.createInterface({ input: process.stdin, output: process.stdout });
rl.question("What do you think of node.js? ", function(answer) {
  console.log("Thank you for your valuable feedback:", answer);
  rl.close();
});
```
With the readline code to make sure the node process stays alive - the footprint for a node process using only readline is 16MB, so fontkit is taking up a tremendous amount of space without having started doing anything.

I don't have any pointers right now that might bring that footprint down, but thought it worth filing as an issue to revisit.

**Comment by devongovett** [comment]
My guess is that it's [brotli](https://github.com/devongovett/brotli.js), which is the compression format used by WOFF2. It's an Emscripten compile, so there is probably a huge typed array in there...

**Comment by devongovett** [comment]
Not seeing that high memory usage either. Looks like about 28MB to me running your snippet unchanged, or 13MB with brotli disabled. How did you measure, what version of node are you running, what OS, etc?

**Comment by Pomax** [comment]
Windows 7, running node 0.12.7

**Comment by Pomax** [comment]
Memory analysis using node-inspector shows a massive amount of memory used by `JSArrayBufferData` objects.

![screenshot 51](https://cloud.githubusercontent.com/assets/177243/8660735/a04080b8-2967-11e5-815b-4f595c8198c8.png)

**Comment by devongovett** [comment]
Can you comment out the `require('brotli')` call in `node_modules/fontkit/src/WOFF2Font.js` and try it?

**Comment by Pomax** [comment]
With brotli's requirement simply set to `var brotli = false; // require('brotli');` the memory footprint drops to a paltry 34MB, so it looks like brotli is doing really weird things on Windows...

**Comment by devongovett** [comment]
Grr. I wanted to do a real JS port rather than use an Emscripten compile anyway, because the Emscripten generated source is really huge, which sucks for browsers. Guess this is just another reason.

**Comment by Pomax** [comment]
how do you want to track? close this issue and open a new on on the brotli repo, or keep this one open as reminder?

**Comment by devongovett** [comment]
https://github.com/devongovett/brotli.js/issues/3
