### ISSUE TITLE
Outputted subset font not working

### ISSUE THREAD

**Issue by pudility** [devongovett/fontkit#159]
I ran the code from the example however, when I tried to install the font - it gave some errors. 
1. `'sfnt' requires tables`
2. `System Validation`

### Environment:
 - MacOS
 - Node.js Version: `v8.11.1`
 - fontkit Version: `1.7.7`

**Comment by bbqaaq** [comment]
Just read the README file.

'Currently, subsets produce minimal fonts designed for PDF embedding that may not work as standalone files. They have no cmap tables and other essential tables for standalone use. This limitation will be removed in the future.'

The subset font file isn't a complete one, so it can't be used as normal as the original font file.

**Comment by pudility** [comment]
That is to bad, thanks for the help though.
