### ISSUE TITLE
Not working in browser

### ISSUE THREAD

**Issue by frankietaylor** [devongovett/fontkit#19]
Output generated with 
browserify index.js -o out.js

when ran in browser throws the following error:
Uncaught TypeError: Cannot read property 'replace' of undefined

Using the github source.

**Comment by samjohn** [comment]
brotli is looking for process.argv[1], which won't be defined in the browser. As a work around, if you're using browserify:

```
if (global.process.argv.length < 2) {
    global.process.argv.push('');
}
```

**Comment by defue** [comment]
I can't make it work in browser either. Compiled it with browserify, fixed the errors in the compiled file. But after the compiled js file is loaded in browser (without) errors I still can't access neither fontkit or require function thus the example from Readme.md doesn't work. Could someone please point me out how to correctly compile and use fontkit in browsers?

**Comment by defue** [comment]
I got it to work . I created a file compile.js with the below content.
`fontkit = require('fontkit');`
And compiled it using browserify
`browserify compile.js -o fontkit.js`
Then added fontkit.js in script tag to browser and then I was able to use fontkit object in my scripts.

**Comment by defue** [comment]
The result fonkit.js is 1.1 MB or 840KB minified. Does anyone know how to reduce the size?

**Comment by devongovett** [comment]
The huge part is WOFF2 support (Emscripten compile). You can make a custom build using only the font formats you need to support.

```javascript
var fontkit = require('fontkit/base');
fontkit.registerFormat(require('fontkit/src/TTFFont'));
```

You can see all the formats supported in the [default configuration](https://github.com/devongovett/fontkit/blob/master/index.coffee).

**Comment by Pomax** [comment]
Remember that the example in the readme is an offline/server-side node example. If you're bundling, make sure to use the correct syntax: bundlers don't magically create "for the web" bundles, you need to tell them what to do. In the case of browserify, you need to use the --standalone flag, and you probably need to tell it to shim the global nodejs `process` variable. If you're using webpack, you need to tell it that it's build for the "web" target. If you're using any other bundler, the same process applies: make sure you're using the syntax require to turn "not for the browser" code into "for the browser" code.

**Comment by mehcode** [comment]
@devongovett Can you please respond to https://github.com/devongovett/atom-stylus/issues/4 ?

It's a fairly easy process. We just need you to change the package name and deprecate the package. Please and thank you.
