### ISSUE TITLE
Support for Source Han Sans or Noto Sans CJK fonts (OpenType)

### ISSUE THREAD

**Issue by mmejia27** [devongovett/fontkit#23]
Hello,

I've been trying to use fontkit with pdfkit (fontkit branch) in order to generate PDFs with Chinese characters. Currently, the best free fonts for supporting CJK are OTF fonts, such as Source Han Sans and Noto Sans, but they don't seem to be supported in fontkit. Using either the superset .ttc, or individual .otf fonts from these projects results in an error of the format not being supported. From my initial digging into the repo, it looks like opentype support isn't wired in yet, correct?

**Comment by devongovett** [comment]
What is the error message you're getting?

**Comment by Pomax** [comment]
I tried the following code with Noto CJK (Japanese otf version) Regular:
```
var fontkit = require('fontkit');
var fs = require('fs');

var font = fontkit.openSync('NotoSansCJKjp-Regular.otf');
var run = font.layout('こりゃどうも');
var aw = 0;
var svg = run.glyphs.map((g,i) => {
  var g = [
    "  <g transform='translate("+aw+",0)'>",
    "    <path fill='black' d='"+g.path.toSVG()+"'/>",
    "  </g>"
  ].join('\n');
  aw += run.positions[i].xAdvance;
  return g;
});

svg = [
  "<svg width='"+aw+"' height='0' viewBox='0 0 "+aw+" 1000'>",
  "<g transform='translate(0,1000) scale(1,-1)'>",
  svg.join('\n'),
  "</g>",
  "</svg>"
].join('\n');

fs.writeFileSync("test.svg", svg);
```
And that works just fine.

http://jsbin.com/lipuwinamu/edit?html,css,output

**Comment by mmejia27** [comment]
This is the error message I receive: "Not a supported font format or standard PDF font." 

Just to make sure I'm not causing confusion, I'm using fontkit within pdfkit (fontkit branch from github) and running in NodeJS (v0.10.36 and v0.12.9).

**Comment by devongovett** [comment]
Sounds like a PDFKit problem, not a fontkit problem. How are you passing your font to PDFKit? String paths, Buffers, Uint8Arrays, or ArrayBuffers are supported.

**Comment by Pomax** [comment]
On a side note, you probably want to update your Node.js to 5.6 (or even 4.3LTS), as that uses a much newer version of V8, with many improvements.

**Comment by mmejia27** [comment]
@devongovett I'm using string paths at the moment.

@Pomax I use the latest on most projects, but in this case, our code runs on AWS Lambda and they are stuck in the dark ages.

**Comment by Pomax** [comment]
@mmejia27 that might also be part of it then. A look at what AWS Lambda supports gives us Node 0.10, which is *incredibly* out of date, and might very well rely on a version of V8 so old that it doesn't support some of the things that we've since come to rely on for binary data parsing...

**Comment by devongovett** [comment]
The tests pass in node 0.10 on Travis, so I don't think that's the issue. Are you certain the file exists where you think it does? Can you try running your program locally? Same issue?

**Comment by mmejia27** [comment]
I have been running this code locally against 0.10.36. I haven't deployed this yet to Lambda because I haven't gotten it to work. I'm in the process of pulling in all the projects again to see if that helps.

**Comment by devongovett** [comment]
If you can, please post a code snippet that reproduces the issue. Also, if you can send a link to the font file you're using, that would help as well.

**Comment by Pomax** [comment]
If it helps, I grabbed the Japenese noto from https://www.google.com/get/noto by filtering for Japanese and the downloading the Noto CJK Regular variant for that language. (There's multiple files because different CJK languages can have different ways to write the same unicode character)

**Comment by mmejia27** [comment]
@devongovett Thanks for asking me to do this as it helped find the real issue. Turns out npm wasn't installing the fontkit branch of pdfkit. When I tried doing the snippet to re-create the issue, I kept on getting an error that it couldn't find pdfkit. Looks like there might be an issue in using github references in npm. I ended up using a local module and it picked it right up and I was able to use my font.

Now I have run into a slightly different issue. It looks link a bunch of the characters are missing in my generated PDF whenever a colon is used in the text. Below is the snipped to re-create the issue.

This is the font I am using: https://github.com/googlei18n/noto-cjk/blob/master/NotoSansCJKsc-Regular.otf

Below is my snippet:

`var PDFDocument = require('../pdfkit');
var fs = require('fs');

var pdfFile = 'test.pdf';
var fontFile = 'NotoSansCJKsc-Regular.otf';
var doc = new PDFDocument({  bufferPages: true });
var pdfStream = fs.createWriteStream(pdfFile);
doc.pipe(pdfStream);

doc.fontSize(12)
   .font(fontFile)
   .text("This is a test: The quick brown fox jumps over the lazy dog.");
   
doc.end();`

**Comment by Pomax** [comment]
How did you trying to install pdfkit? If you installed it with `npm install pdfkit`, you should simply be able to do `require('pdfkit')` directly, rather than loading it from a path?

**Comment by mmejia27** [comment]
@Pomax I was actually trying to install with `npm install git+https://git@github.com/devongovett/pdfkit.git#fontkit` in order to use the fontkit branch. npm seems to install all the modules, but then `require ('pdfkit')` does not find it.

**Comment by devongovett** [comment]
Try `git+ssh` instead of `git+https`

**Comment by devongovett** [comment]
The npm version does not use fontkit yet. That's why you need to use the branch from github.

**Comment by mmejia27** [comment]
@devongovett Using ssh didn't make a difference. I did dig into the node_modules directory and saw pdfkit in there. Inside the directory, though, there's only the LICENSE, Makefile, package.json, and README.md files. A wild guess tells me that maybe npm isn't "smart" enough to know it has to pull the .coffee files and prepublish/run `make js`.

**Comment by devongovett** [comment]
Oh, it's because of the `.npmignore`, which ignores the coffeescript files. Didn't realize npm deleted them after pulling in the repo, assumed that was only used for publishing.

**Comment by mmejia27** [comment]
Interesting! I thought the same thing and didn't even think it could be that. For now I can work with a local module and will see about I can deploy this later on.

Do you think the issue with missing characters after using a colon is a pdfkit issue, or fontkit?

**Comment by Pomax** [comment]
ah, yeah npm (at least, 3) actually does some interesting things - it'll download a package into global cache, clean it out, then use *that* as the base for installing into local dirs.

**Comment by mmejia27** [comment]
@devongovett @Pomax Do you guys have an idea on the issue of characters not displaying if a colon is used in the text?

**Comment by Pomax** [comment]
I can't say I do, does it happen in fontkit, too, or only in pdfkit?

**Comment by mmejia27** [comment]
Well, I don't use fontkit directly in any project, so I can't say for sure. I can say this, though. I'm using pdfkit (from npm) with a regular TTF font and no issues with using a colon there. Using my above snippet reproduces the error with the OTF font. As soon as you remove the colon, though, the rest of the characters show up correctly, so my hunch is something in fontkit.

**Comment by Pomax** [comment]
if you use the code from https://github.com/devongovett/fontkit/issues/23#issuecomment-183814136, does it reproduce in just-fontkit? If not, this is probably an issue to file over on the pdfkit tracker, so that people can find and comment on it there

**Comment by mmejia27** [comment]
So, using that code, I didn't get the same issue. All of the letters came out in the svg, but there was still an issue with the colon. It seems to be printed, but way too far to the left (bad kerning?).

This is the output:
http://jsbin.com/gekatanexo/edit?html,css,output

**Comment by Pomax** [comment]
that could also just be my glyph positioning based solely on the advanceWidth - if the colon does show up (which it seems to) then that feels like a different issue, so I'd recommend filing this over on the pdfkit repo.

**Comment by mmejia27** [comment]
Thanks your help on this! I'll close it out for now as I have opened the issue in pdfkit.
