### ISSUE TITLE
JS Allocation failed - process out of memory

### ISSUE THREAD

**Issue by defue** [devongovett/fontkit#31]
Code:
```
var fontkit = require('fontkit');
var font = fontkit.openSync('SeoulNamsan.ttf');
var run = font.layout('hello world!');
```

When running the code above nodejs process is killed after consuming more than 1GB of RAM with the below error:
```
FATAL ERROR: JS Allocation failed - process out of memory
Aborted (core dumped)
```

Nodejs v0.10.25
Fontkit v1.2.1
[SeoulNamsan.ttf.zip](https://github.com/devongovett/fontkit/files/181852/SeoulNamsan.ttf.zip)

**Comment by devongovett** [comment]
Fixed by the above commits. Was caused by a zero length GSUB table that it tried to decode anyway.
