### ISSUE TITLE
Subset font seems to be broken

### ISSUE THREAD

**Issue by yoheinishikubo** [devongovett/fontkit#40]
I made a subset font with the following script copied from `README.md`.
As a result, the font generated can not be used and previewed with any other applications including Apple's Font Book.

```JS
var fs = require('fs');
var fontkit = require('fontkit');

// open a font synchronously 
var font = fontkit.openSync('SourceSansPro-Regular.otf');

// layout a string, using default shaping features. 
// returns a GlyphRun, describing glyphs and positions. 
var run = font.layout('hellow world!');

// create a font subset 
var subset = font.createSubset();

run.glyphs.forEach(function(glyph) {
    subset.includeGlyph(glyph);
});

subset.encodeStream()
    .pipe(fs.createWriteStream('subset.otf'));
```

**Comment by devongovett** [comment]
As mentioned in the docs:

> Currently, subsets produce minimal fonts designed for PDF embedding that may not work as standalone files. They have no cmap tables and other essential tables for standalone use. This limitation will be removed in the future.

**Comment by yoheinishikubo** [comment]
Very sorry for my misunderstanding.
Can I close this?

**Comment by snoop088** [comment]
Hi,
just to ask as this still seems to be the case. Has adding the proper data to create a subset font become in scope of this library?
thanks
Nick
