### ISSUE TITLE
Test with text-rendering-tests

### ISSUE THREAD

**Issue by brawer** [devongovett/fontkit#49]
Hi Devon, just fyi, the text rendering test suite (the one that was previously in my GitHub space) has now moved to Unicode: https://github.com/icu-project/text-rendering-tests — feel free to use it for testing fontkit. Also, if you’d like to contribute to the test suite, your contributions would be very welcome — I’ll send you the Unicode CLA if you’re interested.

**Comment by devongovett** [comment]
Cool thanks @brawer. I actually already had a fork with fontkit support. I will update it to the latest version. https://github.com/devongovett/fonttest/tree/fontkit

**Comment by brawer** [comment]
Great; attaching [Unicode’s CLA](https://github.com/devongovett/fontkit/files/493400/UnicodeCLA.pdf); if you send a scan with your signature to sascha@brawer.ch I’ll forward it to Unicode. Thanks, and looking forward to more changes...

**Comment by brawer** [comment]
The test suite now takes `--engine=OpenType.js` which invokes JavaScript through NPM. If you want, feel free to make a pull request similar to [this one](https://github.com/unicode-org/text-rendering-tests/commit/489fd485fdd46a8b813b3a9ef71057dba372df96). The [test report for OpenType.js](http://rawgit.com/unicode-org/text-rendering-tests/master/reports/OpenType.js.html) doesn’t look so great yet, but they’re working on improving things; would be curious to see how fontkit looks.

**Comment by devongovett** [comment]
Submitted https://github.com/unicode-org/text-rendering-tests/pull/35!
