### ISSUE TITLE
Glyph mapping wrong

### ISSUE THREAD

**Issue by interactionist** [devongovett/fontkit#5]
Hi there. I was trying out your fontkit, and all worked good for subsetting a font, except that the glyphs are  being mapped to  ```cidxxxx``` instead of their respective unicodes for me and thus not usable. Any clues?

**Comment by devongovett** [comment]
Yes, as [mentioned](https://github.com/devongovett/fontkit#subsets) in the readme, the subsetting support is currently only designed for PDF embedding, which doesn't require a cmap and a number of other tables that are normally required for standalone use.

Eventually, I'd like that to be a mode, along with full standalone subsetting support. Implementing standalone subsetting will be more complicated, especially when other tables like GPOS and GSUB are taken into account.

**Comment by interactionist** [comment]
Thanks.
