### ISSUE TITLE
Typos?

### ISSUE THREAD

**Issue by adrift2000** [devongovett/fontkit#50]
1.
Take a look at the "f" function https://github.com/devongovett/fontkit/blob/master/src/glyph/Path.js#L82
Does it refers to this loop variable: https://github.com/devongovett/fontkit/blob/master/src/glyph/Path.js#L120? But it has been declared using the let keyword so it never be visible to "f".

2.
https://github.com/devongovett/fontkit/blob/master/src/glyph/CFFGlyph.js#L454
https://github.com/devongovett/fontkit/blob/master/src/glyph/CFFGlyph.js#L492
The "i" is undeclared.

**Comment by devongovett** [comment]
Good catches. Probably caused by the somewhat automatic translation from the original CoffeeScript. Can you submit a PR to fix?

**Comment by adrift2000** [comment]
https://github.com/devongovett/fontkit/pull/51
https://github.com/devongovett/fontkit/pull/52

**Comment by devongovett** [comment]
Thanks!
