### ISSUE TITLE
CFF automatic subroutinization

### ISSUE THREAD

**Issue by be5invis** [devongovett/fontkit#55]

**Comment by Pomax** [comment]
making this work efficiently is a good source for a paper or two - naively, it's the byte equivalent of finding the largest common substring in a set of strings, marking it a subroutine, reducing all strings, and then running the algorithm again, repeating the process until there are "common substrings" left, so having a good guide to what is worth turning into substrings, which charstrings are worth not splitting up at all even if they do have something that could conceivably be a substring, which boundaries a substring should not cross, etc. is far from trivial.

**Comment by devongovett** [comment]
Also, currently fontkit doesn't produce fonts from scratch, it only subsets them using the existing subroutines from the original font. Unless we add support for creating fonts from scratch, I think this issue may be better sent to [opentype.js](https://github.com/nodebox/opentype.js), which is more of a font creation library.

**Comment by be5invis** [comment]
@Pomax No, it is the “optimal grammar problem” in the area of data compression.
