### ISSUE TITLE
Correct orientation?

### ISSUE THREAD

**Issue by emrosenf** [devongovett/fontkit#63]
Sorry for the elementary question. I'm following the example from [fonttest](https://github.com/devongovett/fonttest/blob/fontkit/src/fonttest/fontkit.js) to turn a text string into an SVG path. When you load the resulting SVG file in the browser, the glyphs are flipped.

I understand that by convention, the y-axis for SVG points downward whereas for fonts it points upward. My question is: what is the best way to work with the path data so that the glyphs appear with proper orientation? Can I generate the path data so that it appears right-side-up to begin with Should I wrap everything in a `<g transform="scale(1,-1)">`?

**Comment by pixarbasim** [comment]
I am facing the same problem. @emrosenf What solution did you arrive at for this?

**Comment by Pomax** [comment]
this is how fonts work: the coordinate system in OpenType is flipped wrt SVG's coordinate system. Just use a `<g>` transform to flip things as needed.

**Comment by AgainPsychoX** [comment]
How about flipping while printing to canvas? I know it can be done, but its troublesome... Simple optional flag passed to `render` would be really helpful.
