### ISSUE TITLE
Bug in OTProcessor.js - method getClassID

### ISSUE THREAD

**Issue by liborm85** [devongovett/fontkit#65]
Commit https://github.com/devongovett/fontkit/commit/554a005452a3246fe878e695eeff332789529606 introduced a bug that sometimes causes crash - it may be return `undefined`. 

For example:
This lines: https://github.com/devongovett/fontkit/blob/08171fe567b4922325bcd5a268e238501624b890/src/opentype/OTProcessor.js#L237-L240
When `glyph` is `3` and `classDef.startGlyph` is `4`. Variable `i` will be `-1`.
Condition will be valid and will be returned index -1 from array which will `undefined`. And this causes an error in the other methods.
Probably there should be something like:  `if (i > -1 && i < classDef.classValueArray.length) {`

I do not know exactly how it should work, but condition for negative number `i` do not return true.

This bug causes crash in https://github.com/bpampuch/pdfmake when I use any font.

**Comment by devongovett** [comment]
I applied your fix in 26f99b87321f13e6b59537d7444a31c1e8b2a895, and released in v1.5.4. Would like to add a test case for that. Do you have a font that causes this error?

**Comment by liborm85** [comment]
@devongovett Thanks.

Font causes error can download here:
https://github.com/bpampuch/pdfmake/blob/880db373839b3f51eae29259ea93da9afdb99429/examples/fonts/Roboto-Regular.ttf
