### ISSUE TITLE
Bug in GlyphInfo.js

### ISSUE THREAD

**Issue by liborm85** [devongovett/fontkit#66]
Improvements made by commit https://github.com/devongovett/fontkit/commit/b6d4653c7989fd44682211de8023dfac9f1b1c59 in this file
https://github.com/devongovett/fontkit/blob/f84809aafbcc720fd4a912e8624b14193217032b/src/opentype/GlyphInfo.js#L37-L41 causing an error when is defined `this._font.GDEF` but  `this._font.GDEF.glyphClassDef` is `null`.

Is throw error:
`TypeError: Cannot read property 'version' of null`

This bug was reported to pdfmake by @emanuelschuetze. Details in issue: https://github.com/bpampuch/pdfmake/issues/818

**Comment by achrist** [comment]
+1 for this. Also running into the same issue.

**Comment by devongovett** [comment]
Fixed by #72. Released in v1.5.3.
