### ISSUE TITLE
Not a supported font format or standard PDF font.

### ISSUE THREAD

**Issue by Milewski** [devongovett/fontkit#75]
Guys.... the following code is returning me a Buffer instead of string

```
var fontkit = require('fontkit');

var font = fontkit.openSync('source/assets/media/fonts/chinese/STHeiti Light.ttc');

font.fonts.forEach(font =>{
    console.log(font.postscriptName)
    console.log(font.postscriptName.toString('utf8'))
})

//logs
<Buffer 53 54 48 65 69 74 69 54 43 2d 4c 69 67 68 74>
STHeitiTC-Light
<Buffer 53 54 48 65 69 74 69 53 43 2d 4c 69 67 68 74>
STHeitiSC-Light

```

the problem is that due to this (i believe)... i always get wrong mismatching font family names..

```
doc.registerFont('Main', 'source/assets/media/fonts/chinese/STHeiti Light.ttc', 'STHeitiTC-Light')
```

throws me 

```
throw new Error('Not a supported font format or standard PDF font.');
        ^
Error: Not a supported font format or standard PDF font.
```

i think this is the reason because... i was using this script to indentify the font postscriptName and even wrote an entire tutorial internally with pictures demonstrating.. but then sunddenly for the first time it started returning a buffer... odd 

i did manange to get this working before... so i am absolutely sure its not a problem with the font.. as i have few pdf generated using the same script that im using right now... this problem only showed up after i clean up the whole node_modules and installed again due to there were too many modules inside which i had already deleted from my package.json.. then after reinstalling.... got this error..

**Comment by Pomax** [comment]
`ttc` is not a single font but an OpenType font collection, containing multiple individual fonts packed into a single sort-of-archive format. As browsers and many PDF tools don't support collections, unpack the `.ttc` to individual `.ttf` or `.otf` files (depending on which OpenType flavour they are) and then use those individual fonts, instead.

**Comment by Milewski** [comment]
Unpack into a single file could be a solution if I knew how.. However it was perfectly working before.. I believe it's a bug that is making a if statement somewhere down in the core code fails when it compares string === buffer... Maybe it's just a matter of doing something like string === buffer.toString().. Which I will investigate further next week when I get time..

**Comment by Pomax** [comment]
ah I see. In the mean time, there are a few solutions to unpacking a `.ttc`, the one that's the most "guaranteed to do the right thing" is to use [FontForge](https://fontforge.github.io), load the collection, and then `file -> generate` new fonts from the set that loads in. There are some conversion utilities and online converters, but as the de facto libre Font editor for decades now, FontForge is pretty reliable (and you can even automate the task with something like https://gist.github.com/fatum12/941a10f31ac1ad48ccbc)

**Comment by devongovett** [comment]
It is a buffer probably because it is encoded in an encoding that isn't supported out of the box by node. If you install `iconv-lite` alongside fontkit, many more encodings are supported.

**Comment by Milewski** [comment]
i think that would be the reason.. i might had some other non related dependences to fontkit that was briging along some "extras" that fontkit was making use of... after deleting them (and many others) i have no idea which one had the piece needed fiz this puzzle... still i feel it shouldnt return a buffer when it clearly says it returns a string on the docs.. maybe throw an error when it happens? anyway i have solved my problem by doing as pomax said... converting `.ttc` to `.ttf` with FontForge.
