### ISSUE TITLE
Export path to SVG

### ISSUE THREAD

**Issue by pwichmann** [devongovett/fontkit#76]
First of all, thank you very much for the library. This looks super helpful.

I was trying to get an SVG for a string or letter, so that I can further process it in paper.js.

Now, what I receive from this method ```var svg = run.glyphs[0].path.toSVG();``` is not what I expected. I received a complex series like this:

> M219 1233L211 722Q247 712 319 712L397 712L397 755Q397 849 383 1037.5Q369 1226 369 1320Q369 1343 386.5 1358.5Q404 1374 417.5 1374Q431 1374 441 [...]

However, I would have expected a well-formatted XML/SVG string.

I am a total noob as should be obvious by now. But how would I be able to obtain an SVG string from the series above?

**Comment by pwichmann** [comment]
I am indeed stupid. For all other stupid people out there:

What you get is the d-part of the SVG string:

```
<svg height="210" width="400">
  <path d="M150 0 L75 200 L225 200 Z" />
</svg>
```

**Comment by pwichmann** [comment]
Interestingly, the resulting SVG object is horizontally mirrored.

This is a 'G'.

<img width="129" alt="g" src="https://cloud.githubusercontent.com/assets/13521375/24327557/26d09ff2-11cc-11e7-9613-b8aaddbcc14d.png">

**Comment by Harbs** [comment]
That's because the coordinate space for fonts is different than SVG. The original path data is not modified.
See: http://stackoverflow.com/questions/14203365/why-svg-font-is-mirrored

**Comment by Pomax** [comment]
There was some brief discussion around simplifying this task back in https://github.com/devongovett/fontkit/issues/24 but that issue may have fallen off the radar since.

**Comment by pwichmann** [comment]
Don't worry about it, guys!

I just added a horizontal flip to the SVG tags. As simple as that. No headache.

`<svg transform="scale(1,-1)"> <path d="' + svg_data_part + '" /> </svg>`

**Comment by Enelar** [comment]
There still bug, svg path doesn't transformed to center of axis, and actually different for each glyph

**Comment by Pomax** [comment]
@Enelar please file that as a separate issue.
