### ISSUE TITLE
Get buffer of single font in collection

### ISSUE THREAD

**Issue by swampthang** [devongovett/fontkit#81]
I need to embed a font as a base64 string inside an SVG foreignObject to export an image using canvas. If it's a single font file, base64 encoding the font.stream.buffer works great. If it's a collection, I assumed getting the font like this would create a buffer of the font pulled from the collection...
```
// fontData - obj with the path to the ttc file and the postscriptName of the font to pull out
var ext = path.extname(fontData.path),
    fontObj;

if( ext == '.ttc' || ext == '.fdont' ) {
  fontObj = fontkit.openSync(fontData.path, fontData.postscriptName);
} else {
  fontObj = fontkit.openSync(fontData.path);
}
var buff = fontObj.stream.buffer;
```

Instead, it's a buffer of the entire ttc file. Is there a way, within fontkit, to get a base64 of a single font from the collection?

**Comment by swampthang** [comment]
Does anyone know of any way to accomplish this programmatically?

**Comment by swampthang** [comment]
I've resolved this issue another way.

**Comment by Rishab-1065** [comment]
Please tell how you solved this issue.

**Comment by michaeltaranto** [comment]
Curious how you approached the problem from another angle @swampthang, anything you can share?
