### ISSUE TITLE
Console Statement in Build Process - Line 3632

### ISSUE THREAD

**Issue by jayiconcmo** [devongovett/fontkit#87]
In the build process for index.js there is a console.log statement (line 3632) as follows:
`
console.log(this.cmap).
`
This outputs long list of numbers in an object. Thank you in advance for fixing. :)

![snapshot42](https://cloud.githubusercontent.com/assets/14827580/25669146/4e280bd6-2fee-11e7-83a6-bda9c349f447.png)

**Comment by Pomax** [comment]
If you know exactly where it is, it's probably faster to hit the edit button for this file here on github, remove that line, and the scroll down to the bottom of the edit page to turn that into a PR fix without ever having to leave the browser. Really convenient for small fixes like these.

**Comment by dahjelle** [comment]
The `console.log` isn't anywhere in the source on GitHub, though, as far as I can see…perhaps just the NPM published version contained it somehow?

**Comment by devongovett** [comment]
Oops, my bad. I republished in v1.5.8.

**Comment by jayiconcmo** [comment]
Thank you. I have tested it and looks great.
