### ISSUE TITLE
Kannada font support in fontkit

### ISSUE THREAD

**Issue by mpsbhat** [devongovett/fontkit#91]
Hello,
Is there any workarounds for Kannada fonts like LohitKannada.ttf, Baraha.ttf etc?
We can't create pdf in Kannada.

[Refer this link for details](https://github.com/bpampuch/pdfmake/issues/562#event-1071895534)

**Comment by devongovett** [comment]
Yeah, currently fontkit has no indic shaper, which is necessary for correct rendering of Kannada. Here is the OpenType [spec](https://www.microsoft.com/typography/OpenTypeDev/kannada/intro.htm) for Kannada shaping.

To be honest, I'm pretty intimidated by the harfbuzz indic shaper code. I would prefer to start with one script and add more indic scripts over time, but it seems kind of hard to separate out which pieces of logic are for which scripts. Also, each script has its own unicode spec, so figuring out the commonalities between them and what harfbuzz does might be a challenge.

@behdad if you had to do it again, would you do it all as one shaper, or separate ones for each script?

**Comment by behdad** [comment]
Hey Devon.  @brawer and I were talking about you tonight.  We should all get together next time he's in the Bay Area.

> To be honest, I'm pretty intimidated by the harfbuzz indic shaper code. I would prefer to start with one script and add more indic scripts over time, but it seems kind of hard to separate out which pieces of logic are for which scripts. Also, each script has its own unicode spec, so figuring out the commonalities between them and what harfbuzz does might be a challenge.

I certainly feel for you.

> @behdad if you had to do it again, would you do it all as one shaper, or separate ones for each script?

I think I'll do it exactly the same way.  I think @jfkthame agrees.  You can watch this presentation of mine about the intricacies of that piece of code and why it was developed in that way:

  https://www.youtube.com/watch?v=sMkO4gF4-3U

I remember you have a decent ragel replacement.  I suggest you just do an exact translation of the code.  I know for other shapers you did a lot of simplification and JS-ification.  Given that the main feat of the Indic shaper is to match windows output, it would be a lost cause to do an open interpretation of it.

Anyway, back to your point about not being clear which parts apply to which script, it's not that bad.  There's the `indic_config_t` stuff, which is easy to navigate, then there's a handfull of script-specific blocks of code, you can find by searching the file for `HB_SCRIPT_`.

HTH!

**Comment by devongovett** [comment]
> Hey Devon. @brawer and I were talking about you tonight. We should all get together next time he's in the Bay Area.

That would be great! Let me know.

Thanks for the advice. I probably will end up porting the code as closely as I can.

**Comment by devongovett** [comment]
Started implementation. Watch the [indic](https://github.com/devongovett/fontkit/compare/devongovett:master...devongovett:indic) branch for progress. Will also post updates here as I go.

**Comment by mpsbhat** [comment]
Great..!!! We hope a good solution for Kannada PDF generation.

**Comment by devongovett** [comment]
Made some good [progress](https://github.com/devongovett/fontkit/compare/devongovett:master...devongovett:indic) on this today. Now passing all 81 Kannada test cases from [text-rendering-tests](https://github.com/unicode-org/text-rendering-tests)!

<img width="830" alt="screen shot 2017-05-21 at 2 04 54 am" src="https://cloud.githubusercontent.com/assets/19409/26282644/f5e4f738-3dc9-11e7-95bb-f020283a54fa.png">

Still lots of work to do though. I only implemented the subset of features needed to pass those tests. So for other scripts, and more advanced sequences, more behavior is needed. Will need test cases to work against. Also the code is a bit of a mess at the moment, so that will need to be cleaned up too.

**Comment by mpsbhat** [comment]
That's splendid work @devongovett ...!!!

Mr @liborm85 was made a test script [here](https://github.com/bpampuch/pdfmake/issues/562#issuecomment-302949363) using pdfmake + fontkit-dev with kannada/indic support and it is working perfectly as desired. Attached the pdf screenshot for reference. It take few seconds to generate pdf and we think it may resolved once code is cleaned.
![screenshot from 2017-05-22 11 28 53](https://cloud.githubusercontent.com/assets/9914694/26294619/bec880fc-3ee2-11e7-85c2-4fb2cdf27d14.png)

**Comment by devongovett** [comment]
See #99.

**Comment by devongovett** [comment]
Merged and released in v1.7.1 (messed up v1.7.0).

**Comment by davelab6** [comment]
This is an amazing work Devon! Congrats!

**Comment by mpsbhat** [comment]
Well, Thank you very much @devongovett ...!!!

We like to be a coder like you :100:
