### ISSUE TITLE
Performance penalty of TTF fonts vs builtin fonts

### ISSUE THREAD

**Issue by ramaza** [devongovett/fontkit#97]
It seems there was a huge performance improvement since I last reported a TTF font performance issue. Many thanks for that work! In the past generating long reports with TTF font was hardly possible for me.

Anyway, I would like to ask if it's normal that PDF generation (with pdfkit) still takes twice as long with TTF font than with builtin font. It's not a show-stopper. I think I just want to understand if there is an inevitable performance penalty with using TTF fonts.

Example:
Builtin Helvetica = 5 seconds for a 128 page report
TTF Open Sans = 10 seconds for same report

**Comment by devongovett** [comment]
This is somewhat expected. Layout of OpenType is far more complex than layout of builtin PDF fonts. The OpenType layout model allows for very complex text processing (substitutions, etc.) that the builtin PDF fonts simply do not. That said, if there are opportunities for optimizations in fontkit, I would love to make them. Do some profiling and see what is slow, and we'll see if we can make it faster or not.
